In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('dataset/synthetic_logs.csv')
df.head()

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert

In [4]:
df.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI', 'LegacyCRM'], dtype=object)

In [5]:
df.target_label.unique()

array(['HTTP Status', 'Critical Error', 'Security Alert', 'Error',
       'System Notification', 'Resource Usage', 'User Action',
       'Workflow Error', 'Deprecation Warning'], dtype=object)

In [6]:
!pip install sentence-transformers
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN

Requirement already satisfied: sentence-transformers in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (5.3.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from sentence-transformers) (4.49.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from sentence-transformers) (0.29.1)
Requirement already satisfied: torch>=1.11.0 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from sentence-transformers) (2.6.0)
Requirement already satisfied: numpy in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from sentence-transformers) (1.26.4)
Requirement already satisfied: scikit-learn in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from sentence-transformers) (1.5.1)
Requirement already satisfied: scipy in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from sentence-transformers) (1.14.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from sentence-transformers) (4.66.5)
Requirement already satisfied: filelock in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.12.0)
Requirement already satisfied: packaging>=20.9 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: networkx in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (3.4.2)
Requirement already satisfied: jinja2 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: setuptools in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (75.1.0)
Requirement already satisfied: sympy==1.13.1 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.5.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from scikit-learn->sentence-transformers) (3.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/miniconda3/envs/AI/lib/python3.12/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2026.1.4)

/opt/miniconda3/envs/AI/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'

In [7]:
# load pre-trained SentenceTransformer model
model = SentenceTransformer('all-MiniLM-L6-v2')

# genearate embeddings for long messages
embeddings = model.encode(df['log_message'].tolist())
embeddings[:2]

array([[-1.02939688e-01,  3.35459225e-02, -2.20260657e-02,
         1.55102881e-03, -9.86917876e-03, -1.78956240e-01,
        -6.34410977e-02, -6.01761341e-02,  2.81108525e-02,
         5.99619560e-02, -1.72618404e-02,  1.43374025e-03,
        -1.49560049e-01,  3.15282005e-03, -5.66031225e-02,
         2.71685869e-02, -1.49889700e-02, -3.54038067e-02,
        -3.62936519e-02, -1.45410141e-02, -5.61496196e-03,
         8.75538737e-02,  4.55120839e-02,  2.50963978e-02,
         1.00187724e-02,  1.24266818e-02, -1.39923587e-01,
         7.68696293e-02,  3.14095505e-02, -4.15257411e-03,
         4.36903127e-02,  1.71250589e-02, -8.00950602e-02,
         5.74005991e-02,  1.89091843e-02,  8.55261385e-02,
         3.96398939e-02, -1.34371802e-01, -1.44370692e-03,
         3.06701171e-03,  1.76854134e-01,  4.44883015e-03,
        -1.69275273e-02,  2.24266108e-02, -4.35050204e-02,
         6.09027781e-03, -9.98169277e-03, -6.23972975e-02,
         1.07372301e-02, -6.04900438e-03, -7.14660659e-02,
        -8.45810771e-03, -3.18019502e-02, -1.00518361e-01,
         2.25895477e-04, -1.89341903e-02, -3.17794196e-02,
         4.00860794e-02,  2.19177660e-02, -2.59527788e-02,
         5.84524684e-02, -8.12509730e-02,  2.12028790e-02,
        -5.02687767e-02,  1.32057210e-02,  1.32681523e-03,
         2.27063559e-02, -3.45793776e-02,  3.91547419e-02,
        -2.09433250e-02,  3.24815838e-03,  4.43961136e-02,
        -9.85357687e-02, -2.88894456e-02, -6.85029617e-03,
         5.38819209e-02,  6.46110550e-02, -2.45060381e-02,
         9.21828821e-02, -7.49869496e-02,  1.23995245e-02,
        -1.00026570e-01, -4.64910306e-02,  6.01569861e-02,
        -2.46480722e-02, -7.08075762e-02, -2.77270023e-02,
         9.72611532e-02,  3.85841615e-02, -1.44292414e-02,
        -7.46871112e-04, -1.04305102e-02, -1.61842890e-02,
         4.43628132e-02,  9.25993361e-03,  7.14165494e-02,
         6.37917370e-02,  4.94930819e-02, -6.02567680e-02,
         4.04805727e-02, -3.42860296e-02, -1.93881020e-02,
         6.61234260e-02,  6.01588972e-02,  1.09370947e-02,
        -5.38622774e-03,  1.44579997e-02,  9.25430283e-02,
        -3.14563289e-02, -1.84351597e-02,  9.91879497e-03,
        -1.85575150e-02,  1.31284958e-03,  2.26712673e-05,
         2.02731090e-03,  2.75255814e-02, -4.81927656e-02,
         5.42825349e-02, -7.32066706e-02,  4.88667339e-02,
         4.98490222e-02, -9.01138503e-03, -4.68905345e-02,
        -4.25886698e-02, -8.19524303e-02,  3.87106240e-02,
         7.85502940e-02,  1.46077052e-32,  1.66706182e-02,
         5.25494479e-02, -1.82449967e-02, -1.26686050e-02,
         6.52837008e-02, -2.11777650e-02, -4.06322442e-02,
         4.14948016e-02, -2.48362143e-02, -1.33068189e-02,
        -5.46753146e-02, -5.99133375e-04, -4.89248848e-03,
        -6.27359152e-02, -3.84878479e-02, -6.13543615e-02,
         8.27404931e-02,  2.34380756e-02, -8.63085780e-03,
         1.31002134e-02,  6.44214526e-02, -4.41361554e-02,
        -6.98633939e-02, -7.36060217e-02, -4.33264039e-02,
         6.96523674e-03, -5.05956411e-02, -1.60911698e-02,
        -5.66794351e-02,  3.35451844e-03,  5.34115620e-02,
         2.47761291e-02, -1.47986235e-02, -2.93242633e-02,
         7.30228871e-02, -1.86833385e-02,  8.13136995e-02,
        -2.69968044e-02, -5.68055958e-02, -6.59388453e-02,
        -5.95392147e-03,  2.85313018e-02, -7.85358101e-02,
        -2.76690582e-03, -3.26478668e-03, -9.28333327e-02,
        -7.27363676e-02, -3.31903510e-02,  1.01411052e-01,
         9.79881510e-02, -9.78740454e-02,  1.98668186e-02,
         2.38837097e-02, -1.81672964e-02, -3.73708829e-02,
         1.96556305e-03,  6.34425506e-02,  1.18270433e-02,
        -1.12041337e-02, -3.87316383e-02,  9.32424366e-02,
         4.26634261e-03, -1.66872833e-02, -6.87464252e-02,
         1.55119272e-02, -4.97754999e-02,  3.34492698e-02,
         8.00032616e-02,  2.12281998e-02,  1.34581864e-01,
        -2.30730418e-02,  5.53858466e-02,  3.07558030e-02,
        -2.93905400e-02,  2.31905375e-02, -9.34307575e-02,
         7.58035034e-02, -5.21204341e-03, -5.14523350e-02,
         3.32689732e-02,  3.67963649e-02, -1.06450748e-02,
         1.01635484e-02, -2.07650922e-02, -5.85519560e-02,
         4.79328558e-02,  2.13694703e-02,  8.76212716e-02,
         3.35488841e-03, -3.80336493e-02, -1.81204956e-02,
         6.87440112e-03,  5.15879504e-02, -4.75598983e-02,
        -6.12065196e-02, -1.45483589e-32,  4.12803376e-03,
         4.59641498e-03, -5.63901104e-02,  4.32477333e-03,
        -1.09442836e-03,  9.31956153e-03, -2.20268592e-02,
         5.79565242e-02, -1.44787850e-02,  4.64156009e-02,
         1.43542886e-01, -6.89755976e-02,  6.09631017e-02,
        -8.93744305e-02,  2.40919497e-02,  2.06010286e-02,
        -2.82415897e-02, -6.48316666e-02,  5.64795285e-02,
        -7.48336641e-03, -3.52058411e-02,  8.51059854e-02,
         1.30359493e-02,  2.02258639e-02, -1.44390967e-02,
        -4.63718772e-02,  1.77209731e-02,  1.59105025e-02,
        -9.51009244e-02, -3.54527123e-02,  2.08696388e-02,
         3.84381157e-03, -8.77917781e-02,  6.44574761e-02,
         1.44170718e-02,  3.84730939e-03,  4.70991321e-02,
         4.94661666e-02,  1.53862676e-02, -2.59578601e-02,
         9.10895094e-02,  1.83307733e-02, -5.89206479e-02,
         2.51992997e-02, -3.30374874e-02,  8.23344588e-02,
         1.74791794e-02,  6.48046732e-02, -1.19673889e-02,
        -3.31778117e-02,  3.00177261e-02,  3.54221165e-02,
        -1.39624001e-02,  6.69272766e-02,  3.87919694e-02,
         6.06916063e-02,  1.17962318e-03, -2.38786247e-02,
        -1.26930505e-01,  1.13847358e-02,  1.59290377e-02,
        -1.29426448e-02, -8.63247812e-02,  8.53659492e-03,
         6.03761375e-02,  1.51121970e-02, -1.19132400e-01,
         1.15234423e-02,  5.97088784e-02, -3.93345542e-02,
         1.55674238e-02,  1.04602594e-02, -4.72457074e-02,
        -2.59243567e-02,  9.98527370e-03,  3.07146087e-02,
        -7.14844018e-02,  6.98958710e-03, -1.55133866e-02,
         2.18864474e-02, -2.78145708e-02,  6.92733899e-02,
        -2.75903884e-02,  2.62429044e-02,  3.52562778e-02,
        -4.26419042e-02,  7.46296719e-04,  6.59867302e-02,
        -5.15104756e-02, -3.58433686e-02, -6.53444463e-03,
        -2.75858473e-02, -1.00125603e-01,  7.83325285e-02,
        -1.45799508e-02, -6.18457321e-08,  2.00325307e-02,
         6.59785643e-02, -2.04702113e-02,  1.64044257e-02,
         7.63001218e-02,  7.32182711e-02,  5.65786986e-03,
        -6.97640877e-04, -3.63801536e-03,  6.02394491e-02,
        -3.27187218e-02, -6.45837411e-02, -5.97953424e-02,
        -1.76696014e-02,  6.10145042e-03, -5.63490111e-03,
        -1.22972220e-01,  6.35819063e-02, -2.19431985e-02,
        -1.16406530e-01,  2.34365053e-02, -7.23524541e-02,
         2.31773499e-02, -6.55987933e-02, -7.42682070e-02,
         2.60145944e-02,  3.59758288e-02,  7.68433139e-02,
        -3.08056660e-02, -2.34794449e-02, -6.30426034e-02,
        -3.62157933e-02, -1.03560174e-02, -4.75602821e-02,
        -2.87521537e-02,  2.96401326e-02, -5.26904408e-03,
         5.67889847e-02, -3.74486879e-03,  3.09612453e-02,
         3.48227583e-02,  3.78607698e-02,  2.10155770e-02,
         2.70691458e-02,  5.25520444e-02,  7.16230199e-02,
        -5.53753879e-03,  4.01093699e-02,  5.16275726e-02,
        -2.67314501e-02,  5.94224818e-02, -4.29224074e-02,
        -1.19761080e-02,  3.05986349e-02, -7.40331411e-02,
         1.84221677e-02, -8.64861999e-03, -8.83557945e-02,
        -5.91983721e-02, -1.00885161e-04,  1.12913601e-01,
         4.57783183e-03, -4.25971448e-02,  3.22624156e-03],
       [ 8.04574229e-03, -3.57392617e-02,  4.93873768e-02,
        -7.19190203e-03,  6.17666868e-04, -9.05684903e-02,
         5.75594939e-02, -4.39445600e-02,  1.74751375e-02,
         5.21202609e-02, -4.62332778e-02,  2.49038953e-02,
         4.80811037e-02,  6.86636493e-02,  3.56147178e-02,
         3.00088748e-02,  2.61450745e-02, -9.05242190e-02,
        -8.02173018e-02,  5.04851006e-02, -7.90870637e-02,
        -1.76852697e-03, -2.48927288e-02,  9.02152881e-02,
         5.83696971e-03, -6.91071451e-02, -6.67965561e-02,
        -6.99115265e-03, -1.04566067e-01, -2.66474243e-02,
         3.05640977e-02,  2.02934425e-02,  2.25454438e-02,
        -4.22683870e-03,  1.11172944e-02,  6.78260699e-02,
         1.06073245e-02,  7.56636262e-02, -8.22778493e-02,
         8.45731515e-03, -6.97612017e-02, -4.21973802e-02,
        -1.05675226e-02,  2.23673470e-02,  5.64496815e-02,
         8.16499442e-03,  1.09344058e-01,  3.16564888e-02,
        -1.76924355e-02, -3.21071446e-02, -3.39975730e-02,
        -4.91852988e-04,  3.72879533e-03,  2.83772182e-02,
        -1.28521156e-02, -1.07931253e-03, -6.32418543e-02,
         6.89900815e-02,  1.77270155e-02, -5.20959273e-02,
         8.28306284e-03,  5.45032173e-02, -5.42099290e-02,
        -4.53333072e-02, -4.07494493e-02, -2.82698125e-02,
         1.23605942e-02, -2.13816129e-02, -2.36266032e-02,
         1.25318216e-02, -2.37170905e-02,  3.97411250e-02,
        -1.24362171e-01,  7.60625526e-02,  5.50834015e-02,
         8.28216970e-02,  2.97119021e-02, -1.84067711e-02,
        -1.96194351e-02,  5.54319769e-02, -3.49144079e-02,
        -4.14677300e-02, -3.37047875e-02,  7.31324703e-02,
         4.41836752e-02,  2.55246069e-02, -8.26405175e-03,
        -1.07323108e-02, -4.26243506e-02, -2.84959353e-03,
         7.38559365e-02,  2.27768552e-02,  7.15337170e-04,
         4.36012223e-02,  5.09080067e-02,  6.38482049e-02,
        -2.73155216e-02, -6.55021966e-02, -7.69265667e-02,
         3.55171040e-02,  9.60494205e-02,  2.18195617e-02,
         1.20155066e-02, -1.17863985e-02, -4.57930751e-03,
        -8.58032424e-03,  3.37149873e-02,  2.31918134e-02,
        -7.58325756e-02, -5.23878857e-02,  4.53933813e-02,
        -3.80785577e-02, -3.34904604e-02,  9.20352936e-02,
         2.87688952e-02, -3.33817638e-02, -1.95856881e-03,
        -3.04538000e-04, -1.70498360e-02,  2.85336263e-02,
        -8.81096274e-02, -4.02252525e-02, -4.00093496e-02,
        -1.03192544e-02, -2.51968447e-02,  2.14092918e-02,
         1.31045207e-01, -5.29632847e-34, -1.09651700e-01,
         1.29811335e-02,  5.92660904e-03,  4.73506823e-02,
        -8.60297307e-03, -3.67089771e-02,  3.05215027e-02,
         5.53067103e-02, -4.71985489e-02, -1.25118876e-02,
        -1.15366489e-01,  9.08005331e-03,  1.07346505e-01,
        -4.94734719e-02, -1.34290578e-02, -4.61562276e-02,
         2.45319717e-02,  9.45081469e-03,  2.04324275e-02,
        -3.99918631e-02, -4.67826277e-02,  2.21171305e-02,
        -4.58187200e-02, -8.13270733e-03, -7.65669905e-03,
         1.92284044e-02,  4.85844947e-02, -2.55902875e-02,
         1.61547656e-03, -1.37180435e-02,  9.67296958e-03,
         7.36413011e-03,  1.14088207e-02,  1.28853515e-01,
         7.71840429e-03,  7.06362650e-02,  2.54451223e-02,
         4.06524688e-02,  2.44039744e-02,  1.43776629e-02,
        -6.00932166e-02,  7.38180801e-02, -2.44701374e-02,
         8.98901671e-02,  3.17051820e-03,  1.01834469e-01,
         4.17741686e-02, -5.95178083e-02, -3.23181525e-02,
         3.80938984e-02,  1.21155605e-02, -4.07834500e-02,
         2.84823067e-02,  4.90988977e-02, -9.35701933e-03,
         6.50074631e-02,  7.23532438e-02, -1.67792570e-02,
        -8.22415669e-03, -1.61573309e-02,  5.96225671e-02,
        -3.36083546e-02,  2.12108139e-02, -6.06090575e-02,
         1.54377624e-01, -7.24146068e-02, -3.77272330e-02,
        -3.26889828e-02, -1.80381816e-03, -1.01960078e-02,
        -1.60678080e-03, -6.91846907e-02,  8.28444585e-02,
         9.88840163e-02,  3.45475948e-03, -9.90247652e-02,
        -3.52827124e-02, -7.13179186e-02, -4.96000871e-02,
        -3.43955047e-02, -8.13041851e-02,  4.81447838e-02,
         5.00679482e-03, -2.21499912e-02, -5.60056530e-02,
         1.00068087e-02, -3.59793305e-02,  1.06184371e-01,
        -4.54197228e-02,  7.16393068e-02, -2.36773081e-02,
         9.98138357e-03,  2.73601953e-02,  1.05985515e-01,
         4.60164212e-02,  9.59028719e-34, -1.12306967e-01,
         2.78912112e-02, -3.35900597e-02,  5.39242513e-02,
        -2.22290829e-02,  1.53768994e-02,  3.10411472e-02,
         3.39010768e-02,  7.43167177e-02,  3.42471227e-02,
        -3.35057103e-03, -2.05350965e-02, -3.62370387e-02,
         2.29334682e-02, -3.01991496e-02, -1.00819930e-01,
         3.29193808e-02,  6.77542910e-02,  1.35645103e-02,
        -5.20547619e-03, -6.58158883e-02,  9.54550430e-02,
        -1.34039056e-02,  1.53884459e-02, -7.22936168e-02,
         9.67835858e-02, -8.08119550e-02, -4.53450345e-03,
        -6.42010793e-02, -4.99278717e-02,  4.64197546e-02,
         2.21340507e-02,  3.13109607e-02,  9.13568363e-02,
        -4.61120158e-02, -1.02761105e-01,  3.04415841e-02,
         5.09875864e-02,  6.70140460e-02,  1.04042329e-02,
         1.63533594e-02,  3.92030962e-02,  2.17154324e-02,
         5.36603667e-02,  3.62809598e-02, -4.22140025e-02,
        -2.47227028e-02,  1.90312043e-02,  3.61724310e-02,
         6.37021139e-02, -3.21579445e-03, -8.50385893e-03,
         3.94655913e-02,  9.02656745e-03,  1.93095636e-02,
         6.60717338e-02,  1.02695189e-02, -4.43854034e-02,
        -1.56523399e-02, -1.55714359e-02,  1.32903717e-02,
        -1.16108796e-02,  4.21832018e-02, -5.44777066e-02,
         1.29237175e-01, -2.25756876e-02,  5.26203588e-02,
        -1.58437770e-02,  9.33165029e-02,  6.38027210e-03,
        -9.36164334e-03, -6.08875342e-02, -3.27308029e-02,
        -3.44816744e-02,  3.29973586e-02, -4.79391590e-02,
        -9.81301516e-02,  2.91165188e-02, -2.70903762e-02,
         1.81867238e-02, -1.73860174e-02, -4.40371670e-02,
        -7.97002241e-02,  3.01646534e-02, -6.35260865e-02,
         1.25963567e-02,  8.50249901e-02, -4.58911024e-02,
         5.81017546e-02, -2.71002371e-02,  8.42775777e-02,
        -4.09972891e-02, -3.37656476e-02,  1.02088191e-02,
        -2.54192743e-02, -1.40610279e-08,  4.94446903e-02,
        -9.04356167e-02, -6.06709756e-02,  8.29529315e-02,
        -3.29032615e-02,  4.14910950e-02,  9.99593642e-03,
         6.96135173e-03,  3.99231026e-03, -3.24333534e-02,
        -3.14657316e-02, -5.33161424e-02, -3.80912162e-02,
         1.62077323e-02,  2.45778915e-02, -7.26419240e-02,
        -6.56893328e-02, -8.23131651e-02, -8.00500512e-02,
        -5.36648445e-02,  5.60894832e-02, -1.10913143e-02,
         9.62114253e-04, -1.22690298e-01, -5.13836555e-02,
         9.96704865e-03,  1.00696087e-02,  1.07073054e-01,
         1.19758118e-02,  1.00423442e-02, -6.28261715e-02,
        -7.49697015e-02, -6.34073000e-03, -2.72201169e-02,
        -1.28096193e-01, -2.62459647e-02, -1.81465000e-02,
        -9.85360295e-02, -3.02990358e-02, -4.02615331e-02,
         9.94290337e-02,  5.35999760e-02,  2.74900086e-02,
        -5.53682400e-03,  8.43571052e-02,  8.35161880e-02,
         3.74304615e-02,  7.11937919e-02,  2.98902560e-02,
         2.32728478e-02, -3.62112336e-02,  6.20540008e-02,
         2.15147659e-02,  5.19731976e-02,  1.45338280e-02,
        -4.60966304e-02,  5.02554141e-02, -7.27027953e-02,
         2.92778742e-02,  5.62662631e-02, -3.86355259e-02,
         1.53831728e-02, -6.23095073e-02, -2.77466737e-02]], dtype=float32)

In [8]:
# Perform DBSCAN clustering
dbscan = DBSCAN(eps=0.2, min_samples=1, metric='cosine')
clusters = dbscan.fit_predict(embeddings)

# Add cluster labels to the Dataframe
df['cluster'] = clusters

In [9]:
df.head()

,timestamp,source,log_message,target_label,complexity,cluster
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0

In [10]:
df[df.cluster==5]

,timestamp,source,log_message,target_label,complexity,cluster
8,2025-02-12 10:42:29,ThirdPartyAPI,nova.compute.claims [req-a07ac654-8e81-416d-bf...,Resource Usage,bert,5
26,2025-03-03 17:11:11,ModernCRM,nova.compute.claims [req-d6986b54-3735-4a42-90...,Resource Usage,bert,5
40,2025-06-19 21:42:34,ThirdPartyAPI,nova.compute.claims [req-72b4858f-049e-49e1-b3...,Resource Usage,bert,5
58,2025-09-13 14:45:14,AnalyticsEngine,nova.compute.claims [req-5c8f52bd-8e3c-41f0-95...,Resource Usage,bert,5
61,2025-04-27 11:18:18,ThirdPartyAPI,nova.compute.claims [req-d38f479d-9bb9-4276-96...,Resource Usage,bert,5
...,...,...,...,...,...,...
2336,2025-12-10 11:53:33,AnalyticsEngine,nova.compute.claims [req-97fcea79-42f7-4241-9b...,Resource Usage,bert,5
2345,2025-12-22 01:38:48,BillingSystem,nova.compute.claims [req-caeb3818-dab6-4e8d-9e...,Resource Usage,bert,5
2352,2025-02-18 00:16:44,ModernCRM,nova.compute.claims [req-98474cd9-61e1-4afe-bd...,Resource Usage,bert,5
2355,2025-11-28 18:03:55,BillingSystem,nova.compute.claims [req-6f9ecdfe-481c-4535-9b...,Resource Usage,bert,5
2372,2025-08-07 05:49:03,ThirdPartyAPI,nova.compute.claims [req-01d570b0-78a7-4719-b7...,Resource Usage,bert,5

In [11]:
cluster_counts = df['cluster'].value_counts()
large_clusters = cluster_counts[cluster_counts > 10].index
large_clusters

Index([ 0,  5, 11, 13,  7,  8, 21,  3,  4, 17, 32,  6, 16, 20,  9,  1, 10, 34,
       14, 53, 52, 18, 25, 42, 59, 26],
      dtype='int64', name='cluster')

In [12]:
for cluster in large_clusters:
    print(f"Cluster {cluster}:")
    print(df[df['cluster'] == cluster]['log_message'].head(5).to_string(index=False))
    print()

Cluster 0:
nova.osapi_compute.wsgi.server [req-b9718cd8-f6...
nova.osapi_compute.wsgi.server [req-4895c258-b2...
nova.osapi_compute.wsgi.server [req-ee8bc8ba-92...
nova.osapi_compute.wsgi.server [req-f0bffbc3-5a...
nova.osapi_compute.wsgi.server [req-2bf7cfee-a2...

Cluster 5:
nova.compute.claims [req-a07ac654-8e81-416d-bfb...
nova.compute.claims [req-d6986b54-3735-4a42-907...
nova.compute.claims [req-72b4858f-049e-49e1-b31...
nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a...
nova.compute.claims [req-d38f479d-9bb9-4276-968...

Cluster 11:
User User685 logged out.
 User User395 logged in.
 User User225 logged in.
User User494 logged out.
 User User900 logged in.

Cluster 13:
Backup started at 2025-05-14 07:06:55.
Backup started at 2025-02-15 20:00:19.
  Backup ended at 2025-08-08 13:06:23.
Backup started at 2025-11-14 08:27:43.
Backup started at 2025-12-09 10:19:11.

Cluster 7:
Multiple bad login attempts detected on user 85...
Multiple login failures occurred on user 9052 a...
  User 7153 made multiple incorrect login attempts
  User 8300 made multiple incorrect login attempts
Multiple login failures were detected for user ...

Cluster 8:
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.

Cluster 21:
System updated to version 3.9.1.
System updated to version 5.5.4.
System updated to version 4.7.4.
System updated to version 3.7.7.
System updated to version 2.6.2.

Cluster 3:
         Shard 6 replication task ended in failure
Data replication task for shard 14 did not comp...
         Data replication task failed for shard 17
            Replication of data to shard 14 failed
Data replication task for shard 6 did not complete

Cluster 4:
File data_6169.csv uploaded successfully by use...
File data_3847.csv uploaded successfully by use...
File data_7366.csv uploaded successfully by use...
File data_1206.csv uploaded successfully by use...
File data_1503.csv uploaded successfully by use...

Cluster 17:
Denied access attempt on restricted account Acc...
Unauthorized login attempt on protected account...
   Account Account9437 blocked due to failed login
Account Account7999 access denied due to login ...
Invalid login attempt made on secured account A...

Cluster 32:
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.

Cluster 6:
   Critical system unit error: unit ID Component55
System component malfunction: component ID Comp...
Critical system element is down: element ID Com...
Essential system part malfunction: part ID Comp...
Failure occurred in critical system component: ...

Cluster 16:
System reboot initiated by user User243.
System reboot initiated by user User471.
System reboot initiated by user User216.
System reboot initiated by user User639.
System reboot initiated by user User819.

Cluster 20:
   User 7662 tried to bypass API security measures
User 2367 failed to provide valid API access cr...
        User 3569 made an unauthorized API request
Unauthorized user 2968 tried to access restrict...
User 2186 attempted to access API without prope...

Cluster 9:
Account with ID 5351 created by User634.
Account with ID 7813 created by User373.
Account with ID 9827 created by User965.
Account with ID 2520 created by User546.
Account with ID 2300 created by User964.

Cluster 1:
  Email service experiencing issues with sending
        Email server encountered a sending fault
      Mail service encountered a delivery glitch
Service disruption caused by email sending error
       Email system had a problem sending emails

Cluster 10:
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...
nova.compute.resource_tracker [req-addc1839-2ed...

Cluster 34:
Abnormal behavior found on server 10, possible ...
   Security alert: suspicious activity on server 1
Anomalous activity identified on server 23, sec...
Server 27 experienced potential security incide...
Server 36 experienced potential security incide...

Cluster 14:
   Detection of multiple disk faults in RAID setup
  RAID array suffered multiple hard drive failures
      RAID array experienced multiple disk crashes
Multiple hard drive issues in RAID configuratio...
Identification of multiple faulty disks in RAID...

Cluster 53:
 Module X experienced an invalid data format issue
        Input format mismatch occurred in module X
Module X reported an error in input format vali...
Module X failed to process input due to formatt...
Input data format in module X was invalid or co...

Cluster 52:
Service health check was not successful because...
Invalid SSL certificate resulted in a failed se...
Service health check failure was due to an inva...
An issue with the SSL certificate caused the se...
Service health check failure was caused by an e...

Cluster 18:
Boot process terminated unexpectedly due to ker...
System encountered kernel panic during initiali...
    Boot process was stopped by kernel malfunction
System encountered kernel failure during bootup...
          Boot sequence failed due to kernel panic

Cluster 25:
         System configuration is no longer valid
Configuration is corrupted throughout the system
     Cross-system configuration failure occurred
     System configuration is experiencing errors
        Configuration malfunction is system-wide

Cluster 42:
User 5127 has escalated admin privileges withou...
            User 9745 has escalated to admin level
     User 8483 escalated privileges to admin level
            User 1987 has escalated to admin level
     User 8395 escalated privileges to admin level

Cluster 59:
Potential security threat: Admin privilege esca...
    Admin privilege escalation alert for user 2893
    Admin privilege escalation alert for user 8532
Potential security threat: Admin privilege esca...
Warning: Potential admin privilege escalation f...

Cluster 26:
        Privilege elevation detected for user 5038
Elevation of admin privileges detected for user...
Elevation of admin privileges detected for user...
User 6069 has been granted elevated admin privi...
   Admin privilege elevation warning for user 7574

In [ ]:
import re
def classify_with_regex(log_message):
    regex_patterns = {
        r"User User\d+ logged (in|out).": "User Action",
        r"Backup (started|ended) at .*": "System Notification",
        r"Backup completed successfully.": "System Notification",
        r"System updated to version .*": "System Notification",
        r"File .* uploaded successfully by user .*": "System Notification",
        r"Disk cleanup completed successfully.": "System Notification",
        r"System reboot initiated by user .*": "System Notification",
        r"Account with ID .* created by .*": "User Action"
    }
    for pattern, label in regex_patterns.items():
        if re.search(pattern, log_message):
            return label
    return None

In [14]:
classify_with_regex("User User494 logged out.")

'User Action'

In [15]:
df['regex_label'] = df['log_message'].apply(classify_with_regex)

In [16]:
df.sample(5)

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
1862,2025-01-13 03:15:44,ThirdPartyAPI,nova.osapi_compute.wsgi.server [req-55ebb1b1-6...,HTTP Status,bert,0,None
2053,2025-12-16 17:08:58,ThirdPartyAPI,nova.osapi_compute.wsgi.server [req-f6148ee1-e...,HTTP Status,bert,0,None
982,8/27/2025 2:34,ModernHR,A data export attempt with suspicious paramete...,Security Alert,bert,47,None
612,2025-05-11 16:09:36,AnalyticsEngine,nova.compute.claims [req-caeb3818-dab6-4e8d-9e...,Resource Usage,bert,5,None
1501,3/4/2025 22:32,AnalyticsEngine,Backup completed successfully.,System Notification,regex,8,System Notification

In [17]:
df[df.regex_label.notnull()].shape

(500, 7)

In [18]:
df[df.regex_label.isnull()].shape

(1910, 7)

In [19]:
df_non_reg = df[df['regex_label'].isnull()].copy()
df_non_reg

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,None
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,None
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2,None
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,None
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,None
...,...,...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert,0,None
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert,7,None
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert,0,None
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1,None
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert,7,None

In [21]:
df_non_legacy = df_non_reg[df_non_reg.source != 'LegacyCRM']
df_non_legacy.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI'], dtype=object)

In [23]:
# Generating embeddings for log messages.
filtered_embeddings = model.encode(df_non_legacy['log_message'].tolist())
filtered_embeddings[:2]

array([[-1.02939688e-01,  3.35459225e-02, -2.20260657e-02,
         1.55102881e-03, -9.86917876e-03, -1.78956240e-01,
        -6.34410977e-02, -6.01761341e-02,  2.81108525e-02,
         5.99619560e-02, -1.72618404e-02,  1.43374025e-03,
        -1.49560049e-01,  3.15282005e-03, -5.66031225e-02,
         2.71685869e-02, -1.49889700e-02, -3.54038067e-02,
        -3.62936519e-02, -1.45410141e-02, -5.61496196e-03,
         8.75538737e-02,  4.55120839e-02,  2.50963978e-02,
         1.00187724e-02,  1.24266818e-02, -1.39923587e-01,
         7.68696293e-02,  3.14095505e-02, -4.15257411e-03,
         4.36903127e-02,  1.71250589e-02, -8.00950602e-02,
         5.74005991e-02,  1.89091843e-02,  8.55261385e-02,
         3.96398939e-02, -1.34371802e-01, -1.44370692e-03,
         3.06701171e-03,  1.76854134e-01,  4.44883015e-03,
        -1.69275273e-02,  2.24266108e-02, -4.35050204e-02,
         6.09027781e-03, -9.98169277e-03, -6.23972975e-02,
         1.07372301e-02, -6.04900438e-03, -7.14660659e-02,
        -8.45810771e-03, -3.18019502e-02, -1.00518361e-01,
         2.25895477e-04, -1.89341903e-02, -3.17794196e-02,
         4.00860794e-02,  2.19177660e-02, -2.59527788e-02,
         5.84524684e-02, -8.12509730e-02,  2.12028790e-02,
        -5.02687767e-02,  1.32057210e-02,  1.32681523e-03,
         2.27063559e-02, -3.45793776e-02,  3.91547419e-02,
        -2.09433250e-02,  3.24815838e-03,  4.43961136e-02,
        -9.85357687e-02, -2.88894456e-02, -6.85029617e-03,
         5.38819209e-02,  6.46110550e-02, -2.45060381e-02,
         9.21828821e-02, -7.49869496e-02,  1.23995245e-02,
        -1.00026570e-01, -4.64910306e-02,  6.01569861e-02,
        -2.46480722e-02, -7.08075762e-02, -2.77270023e-02,
         9.72611532e-02,  3.85841615e-02, -1.44292414e-02,
        -7.46871112e-04, -1.04305102e-02, -1.61842890e-02,
         4.43628132e-02,  9.25993361e-03,  7.14165494e-02,
         6.37917370e-02,  4.94930819e-02, -6.02567680e-02,
         4.04805727e-02, -3.42860296e-02, -1.93881020e-02,
         6.61234260e-02,  6.01588972e-02,  1.09370947e-02,
        -5.38622774e-03,  1.44579997e-02,  9.25430283e-02,
        -3.14563289e-02, -1.84351597e-02,  9.91879497e-03,
        -1.85575150e-02,  1.31284958e-03,  2.26712673e-05,
         2.02731090e-03,  2.75255814e-02, -4.81927656e-02,
         5.42825349e-02, -7.32066706e-02,  4.88667339e-02,
         4.98490222e-02, -9.01138503e-03, -4.68905345e-02,
        -4.25886698e-02, -8.19524303e-02,  3.87106240e-02,
         7.85502940e-02,  1.46077052e-32,  1.66706182e-02,
         5.25494479e-02, -1.82449967e-02, -1.26686050e-02,
         6.52837008e-02, -2.11777650e-02, -4.06322442e-02,
         4.14948016e-02, -2.48362143e-02, -1.33068189e-02,
        -5.46753146e-02, -5.99133375e-04, -4.89248848e-03,
        -6.27359152e-02, -3.84878479e-02, -6.13543615e-02,
         8.27404931e-02,  2.34380756e-02, -8.63085780e-03,
         1.31002134e-02,  6.44214526e-02, -4.41361554e-02,
        -6.98633939e-02, -7.36060217e-02, -4.33264039e-02,
         6.96523674e-03, -5.05956411e-02, -1.60911698e-02,
        -5.66794351e-02,  3.35451844e-03,  5.34115620e-02,
         2.47761291e-02, -1.47986235e-02, -2.93242633e-02,
         7.30228871e-02, -1.86833385e-02,  8.13136995e-02,
        -2.69968044e-02, -5.68055958e-02, -6.59388453e-02,
        -5.95392147e-03,  2.85313018e-02, -7.85358101e-02,
        -2.76690582e-03, -3.26478668e-03, -9.28333327e-02,
        -7.27363676e-02, -3.31903510e-02,  1.01411052e-01,
         9.79881510e-02, -9.78740454e-02,  1.98668186e-02,
         2.38837097e-02, -1.81672964e-02, -3.73708829e-02,
         1.96556305e-03,  6.34425506e-02,  1.18270433e-02,
        -1.12041337e-02, -3.87316383e-02,  9.32424366e-02,
         4.26634261e-03, -1.66872833e-02, -6.87464252e-02,
         1.55119272e-02, -4.97754999e-02,  3.34492698e-02,
         8.00032616e-02,  2.12281998e-02,  1.34581864e-01,
        -2.30730418e-02,  5.53858466e-02,  3.07558030e-02,
        -2.93905400e-02,  2.31905375e-02, -9.34307575e-02,
         7.58035034e-02, -5.21204341e-03, -5.14523350e-02,
         3.32689732e-02,  3.67963649e-02, -1.06450748e-02,
         1.01635484e-02, -2.07650922e-02, -5.85519560e-02,
         4.79328558e-02,  2.13694703e-02,  8.76212716e-02,
         3.35488841e-03, -3.80336493e-02, -1.81204956e-02,
         6.87440112e-03,  5.15879504e-02, -4.75598983e-02,
        -6.12065196e-02, -1.45483589e-32,  4.12803376e-03,
         4.59641498e-03, -5.63901104e-02,  4.32477333e-03,
        -1.09442836e-03,  9.31956153e-03, -2.20268592e-02,
         5.79565242e-02, -1.44787850e-02,  4.64156009e-02,
         1.43542886e-01, -6.89755976e-02,  6.09631017e-02,
        -8.93744305e-02,  2.40919497e-02,  2.06010286e-02,
        -2.82415897e-02, -6.48316666e-02,  5.64795285e-02,
        -7.48336641e-03, -3.52058411e-02,  8.51059854e-02,
         1.30359493e-02,  2.02258639e-02, -1.44390967e-02,
        -4.63718772e-02,  1.77209731e-02,  1.59105025e-02,
        -9.51009244e-02, -3.54527123e-02,  2.08696388e-02,
         3.84381157e-03, -8.77917781e-02,  6.44574761e-02,
         1.44170718e-02,  3.84730939e-03,  4.70991321e-02,
         4.94661666e-02,  1.53862676e-02, -2.59578601e-02,
         9.10895094e-02,  1.83307733e-02, -5.89206479e-02,
         2.51992997e-02, -3.30374874e-02,  8.23344588e-02,
         1.74791794e-02,  6.48046732e-02, -1.19673889e-02,
        -3.31778117e-02,  3.00177261e-02,  3.54221165e-02,
        -1.39624001e-02,  6.69272766e-02,  3.87919694e-02,
         6.06916063e-02,  1.17962318e-03, -2.38786247e-02,
        -1.26930505e-01,  1.13847358e-02,  1.59290377e-02,
        -1.29426448e-02, -8.63247812e-02,  8.53659492e-03,
         6.03761375e-02,  1.51121970e-02, -1.19132400e-01,
         1.15234423e-02,  5.97088784e-02, -3.93345542e-02,
         1.55674238e-02,  1.04602594e-02, -4.72457074e-02,
        -2.59243567e-02,  9.98527370e-03,  3.07146087e-02,
        -7.14844018e-02,  6.98958710e-03, -1.55133866e-02,
         2.18864474e-02, -2.78145708e-02,  6.92733899e-02,
        -2.75903884e-02,  2.62429044e-02,  3.52562778e-02,
        -4.26419042e-02,  7.46296719e-04,  6.59867302e-02,
        -5.15104756e-02, -3.58433686e-02, -6.53444463e-03,
        -2.75858473e-02, -1.00125603e-01,  7.83325285e-02,
        -1.45799508e-02, -6.18457321e-08,  2.00325307e-02,
         6.59785643e-02, -2.04702113e-02,  1.64044257e-02,
         7.63001218e-02,  7.32182711e-02,  5.65786986e-03,
        -6.97640877e-04, -3.63801536e-03,  6.02394491e-02,
        -3.27187218e-02, -6.45837411e-02, -5.97953424e-02,
        -1.76696014e-02,  6.10145042e-03, -5.63490111e-03,
        -1.22972220e-01,  6.35819063e-02, -2.19431985e-02,
        -1.16406530e-01,  2.34365053e-02, -7.23524541e-02,
         2.31773499e-02, -6.55987933e-02, -7.42682070e-02,
         2.60145944e-02,  3.59758288e-02,  7.68433139e-02,
        -3.08056660e-02, -2.34794449e-02, -6.30426034e-02,
        -3.62157933e-02, -1.03560174e-02, -4.75602821e-02,
        -2.87521537e-02,  2.96401326e-02, -5.26904408e-03,
         5.67889847e-02, -3.74486879e-03,  3.09612453e-02,
         3.48227583e-02,  3.78607698e-02,  2.10155770e-02,
         2.70691458e-02,  5.25520444e-02,  7.16230199e-02,
        -5.53753879e-03,  4.01093699e-02,  5.16275726e-02,
        -2.67314501e-02,  5.94224818e-02, -4.29224074e-02,
        -1.19761080e-02,  3.05986349e-02, -7.40331411e-02,
         1.84221677e-02, -8.64861999e-03, -8.83557945e-02,
        -5.91983721e-02, -1.00885161e-04,  1.12913601e-01,
         4.57783183e-03, -4.25971448e-02,  3.22624156e-03],
       [ 8.04574229e-03, -3.57392617e-02,  4.93873768e-02,
        -7.19190203e-03,  6.17666868e-04, -9.05684903e-02,
         5.75594939e-02, -4.39445600e-02,  1.74751375e-02,
         5.21202609e-02, -4.62332778e-02,  2.49038953e-02,
         4.80811037e-02,  6.86636493e-02,  3.56147178e-02,
         3.00088748e-02,  2.61450745e-02, -9.05242190e-02,
        -8.02173018e-02,  5.04851006e-02, -7.90870637e-02,
        -1.76852697e-03, -2.48927288e-02,  9.02152881e-02,
         5.83696971e-03, -6.91071451e-02, -6.67965561e-02,
        -6.99115265e-03, -1.04566067e-01, -2.66474243e-02,
         3.05640977e-02,  2.02934425e-02,  2.25454438e-02,
        -4.22683870e-03,  1.11172944e-02,  6.78260699e-02,
         1.06073245e-02,  7.56636262e-02, -8.22778493e-02,
         8.45731515e-03, -6.97612017e-02, -4.21973802e-02,
        -1.05675226e-02,  2.23673470e-02,  5.64496815e-02,
         8.16499442e-03,  1.09344058e-01,  3.16564888e-02,
        -1.76924355e-02, -3.21071446e-02, -3.39975730e-02,
        -4.91852988e-04,  3.72879533e-03,  2.83772182e-02,
        -1.28521156e-02, -1.07931253e-03, -6.32418543e-02,
         6.89900815e-02,  1.77270155e-02, -5.20959273e-02,
         8.28306284e-03,  5.45032173e-02, -5.42099290e-02,
        -4.53333072e-02, -4.07494493e-02, -2.82698125e-02,
         1.23605942e-02, -2.13816129e-02, -2.36266032e-02,
         1.25318216e-02, -2.37170905e-02,  3.97411250e-02,
        -1.24362171e-01,  7.60625526e-02,  5.50834015e-02,
         8.28216970e-02,  2.97119021e-02, -1.84067711e-02,
        -1.96194351e-02,  5.54319769e-02, -3.49144079e-02,
        -4.14677300e-02, -3.37047875e-02,  7.31324703e-02,
         4.41836752e-02,  2.55246069e-02, -8.26405175e-03,
        -1.07323108e-02, -4.26243506e-02, -2.84959353e-03,
         7.38559365e-02,  2.27768552e-02,  7.15337170e-04,
         4.36012223e-02,  5.09080067e-02,  6.38482049e-02,
        -2.73155216e-02, -6.55021966e-02, -7.69265667e-02,
         3.55171040e-02,  9.60494205e-02,  2.18195617e-02,
         1.20155066e-02, -1.17863985e-02, -4.57930751e-03,
        -8.58032424e-03,  3.37149873e-02,  2.31918134e-02,
        -7.58325756e-02, -5.23878857e-02,  4.53933813e-02,
        -3.80785577e-02, -3.34904604e-02,  9.20352936e-02,
         2.87688952e-02, -3.33817638e-02, -1.95856881e-03,
        -3.04538000e-04, -1.70498360e-02,  2.85336263e-02,
        -8.81096274e-02, -4.02252525e-02, -4.00093496e-02,
        -1.03192544e-02, -2.51968447e-02,  2.14092918e-02,
         1.31045207e-01, -5.29632847e-34, -1.09651700e-01,
         1.29811335e-02,  5.92660904e-03,  4.73506823e-02,
        -8.60297307e-03, -3.67089771e-02,  3.05215027e-02,
         5.53067103e-02, -4.71985489e-02, -1.25118876e-02,
        -1.15366489e-01,  9.08005331e-03,  1.07346505e-01,
        -4.94734719e-02, -1.34290578e-02, -4.61562276e-02,
         2.45319717e-02,  9.45081469e-03,  2.04324275e-02,
        -3.99918631e-02, -4.67826277e-02,  2.21171305e-02,
        -4.58187200e-02, -8.13270733e-03, -7.65669905e-03,
         1.92284044e-02,  4.85844947e-02, -2.55902875e-02,
         1.61547656e-03, -1.37180435e-02,  9.67296958e-03,
         7.36413011e-03,  1.14088207e-02,  1.28853515e-01,
         7.71840429e-03,  7.06362650e-02,  2.54451223e-02,
         4.06524688e-02,  2.44039744e-02,  1.43776629e-02,
        -6.00932166e-02,  7.38180801e-02, -2.44701374e-02,
         8.98901671e-02,  3.17051820e-03,  1.01834469e-01,
         4.17741686e-02, -5.95178083e-02, -3.23181525e-02,
         3.80938984e-02,  1.21155605e-02, -4.07834500e-02,
         2.84823067e-02,  4.90988977e-02, -9.35701933e-03,
         6.50074631e-02,  7.23532438e-02, -1.67792570e-02,
        -8.22415669e-03, -1.61573309e-02,  5.96225671e-02,
        -3.36083546e-02,  2.12108139e-02, -6.06090575e-02,
         1.54377624e-01, -7.24146068e-02, -3.77272330e-02,
        -3.26889828e-02, -1.80381816e-03, -1.01960078e-02,
        -1.60678080e-03, -6.91846907e-02,  8.28444585e-02,
         9.88840163e-02,  3.45475948e-03, -9.90247652e-02,
        -3.52827124e-02, -7.13179186e-02, -4.96000871e-02,
        -3.43955047e-02, -8.13041851e-02,  4.81447838e-02,
         5.00679482e-03, -2.21499912e-02, -5.60056530e-02,
         1.00068087e-02, -3.59793305e-02,  1.06184371e-01,
        -4.54197228e-02,  7.16393068e-02, -2.36773081e-02,
         9.98138357e-03,  2.73601953e-02,  1.05985515e-01,
         4.60164212e-02,  9.59028719e-34, -1.12306967e-01,
         2.78912112e-02, -3.35900597e-02,  5.39242513e-02,
        -2.22290829e-02,  1.53768994e-02,  3.10411472e-02,
         3.39010768e-02,  7.43167177e-02,  3.42471227e-02,
        -3.35057103e-03, -2.05350965e-02, -3.62370387e-02,
         2.29334682e-02, -3.01991496e-02, -1.00819930e-01,
         3.29193808e-02,  6.77542910e-02,  1.35645103e-02,
        -5.20547619e-03, -6.58158883e-02,  9.54550430e-02,
        -1.34039056e-02,  1.53884459e-02, -7.22936168e-02,
         9.67835858e-02, -8.08119550e-02, -4.53450345e-03,
        -6.42010793e-02, -4.99278717e-02,  4.64197546e-02,
         2.21340507e-02,  3.13109607e-02,  9.13568363e-02,
        -4.61120158e-02, -1.02761105e-01,  3.04415841e-02,
         5.09875864e-02,  6.70140460e-02,  1.04042329e-02,
         1.63533594e-02,  3.92030962e-02,  2.17154324e-02,
         5.36603667e-02,  3.62809598e-02, -4.22140025e-02,
        -2.47227028e-02,  1.90312043e-02,  3.61724310e-02,
         6.37021139e-02, -3.21579445e-03, -8.50385893e-03,
         3.94655913e-02,  9.02656745e-03,  1.93095636e-02,
         6.60717338e-02,  1.02695189e-02, -4.43854034e-02,
        -1.56523399e-02, -1.55714359e-02,  1.32903717e-02,
        -1.16108796e-02,  4.21832018e-02, -5.44777066e-02,
         1.29237175e-01, -2.25756876e-02,  5.26203588e-02,
        -1.58437770e-02,  9.33165029e-02,  6.38027210e-03,
        -9.36164334e-03, -6.08875342e-02, -3.27308029e-02,
        -3.44816744e-02,  3.29973586e-02, -4.79391590e-02,
        -9.81301516e-02,  2.91165188e-02, -2.70903762e-02,
         1.81867238e-02, -1.73860174e-02, -4.40371670e-02,
        -7.97002241e-02,  3.01646534e-02, -6.35260865e-02,
         1.25963567e-02,  8.50249901e-02, -4.58911024e-02,
         5.81017546e-02, -2.71002371e-02,  8.42775777e-02,
        -4.09972891e-02, -3.37656476e-02,  1.02088191e-02,
        -2.54192743e-02, -1.40610279e-08,  4.94446903e-02,
        -9.04356167e-02, -6.06709756e-02,  8.29529315e-02,
        -3.29032615e-02,  4.14910950e-02,  9.99593642e-03,
         6.96135173e-03,  3.99231026e-03, -3.24333534e-02,
        -3.14657316e-02, -5.33161424e-02, -3.80912162e-02,
         1.62077323e-02,  2.45778915e-02, -7.26419240e-02,
        -6.56893328e-02, -8.23131651e-02, -8.00500512e-02,
        -5.36648445e-02,  5.60894832e-02, -1.10913143e-02,
         9.62114253e-04, -1.22690298e-01, -5.13836555e-02,
         9.96704865e-03,  1.00696087e-02,  1.07073054e-01,
         1.19758118e-02,  1.00423442e-02, -6.28261715e-02,
        -7.49697015e-02, -6.34073000e-03, -2.72201169e-02,
        -1.28096193e-01, -2.62459647e-02, -1.81465000e-02,
        -9.85360295e-02, -3.02990358e-02, -4.02615331e-02,
         9.94290337e-02,  5.35999760e-02,  2.74900086e-02,
        -5.53682400e-03,  8.43571052e-02,  8.35161880e-02,
         3.74304615e-02,  7.11937919e-02,  2.98902560e-02,
         2.32728478e-02, -3.62112336e-02,  6.20540008e-02,
         2.15147659e-02,  5.19731976e-02,  1.45338280e-02,
        -4.60966304e-02,  5.02554141e-02, -7.27027953e-02,
         2.92778742e-02,  5.62662631e-02, -3.86355259e-02,
         1.53831728e-02, -6.23095073e-02, -2.77466737e-02]], dtype=float32)

In [24]:
X = filtered_embeddings
y = df_non_legacy['target_label']

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state=42)
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
report = classification_report(y_test, y_pred)
print(report)

                precision    recall  f1-score   support

Critical Error       0.91      1.00      0.95        48
         Error       0.98      0.89      0.93        47
   HTTP Status       1.00      1.00      1.00       304
Resource Usage       1.00      1.00      1.00        49
Security Alert       1.00      0.99      1.00       123

      accuracy                           0.99       571
     macro avg       0.98      0.98      0.98       571
  weighted avg       0.99      0.99      0.99       571

In [25]:
import joblib

In [28]:
joblib.dump(clf,'../models/log_classifier.joblib')

['../models/log_classifier.joblib']